import { inter, manrope } from "@/config/fonts";
import { cn } from "@/shared/utils/cn";

import "@/shared/styles/globals.css";
import { AppProvider } from "@/shared/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={cn(
          "antialiased font-Manrope tracking-tight",
          inter.variable,
          manrope.variable,
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
